export const NEW_USER = '/new-user'
export const LOGIN = '/login'
export const AUTO_LOGIN = '/auto-login'
export const GET_PROFILE = '/profile/'
export const GET_USERS = '/users'
export const SEND_FRIEND_REQUEST = '/send-friend-request'
export const FRIEND_REQUESTS_NUMBER = '/friend-requests-number'