export const SLASH = '/'
export const UNAUTHENTICATED = '/unauthenticated'
export const PROFILE = '/profile/'
export const FEED = '/feed'
export const FRIENDS= '/friends'
export const CHAT = '/chat'
export const NEW_CHAT = '/new-chat'