version: "3.5"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017"
    networks:
      - MONGO
    volumes:
      - type: volume
        source: MONGO_DATA
        target: /data/db
      - type: volume
        source: MONGO_CONFIG
        target: /data/configdb
  express:
    build:
        context: .
        dockerfile: Dockerfile
    environment:
      MONGO_DB_URI: mongo
    ports:
      - "80:8000"
    networks:
      - MONGO
    depends_on:
      - mongo

networks:
  MONGO:
    name: MONGO

volumes:
  MONGO_DATA:
    name: MONGO_DATA
  MONGO_CONFIG:
    name: MONGO_CONFIG