name: CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14.5.0

      - uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 3.6.8 

      - run: npm ci

      - run: npm run lint

      - run: npm test
